"""First migration

Revision ID: 3c875d8db205
Revises:
Create Date: 2024-10-27 20:53:30.088194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c875d8db205'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('to_place', sa.JSON(), nullable=False),
    sa.Column('from_place', sa.JSON(), nullable=False),
    sa.Column('to_place_title', sa.VARCHAR(), nullable=False),
    sa.Column('from_place_title', sa.VARCHAR(), nullable=False),
    sa.Column('transport_type', sa.VARCHAR(), nullable=False),
    sa.Column('isEnded', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['user.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    op.drop_table('user')
    # ### end Alembic commands ###