"""add column route

Revision ID: 5aa93df9d53f
Revises: 88a0f6bce924
Create Date: 2024-12-09 15:28:36.735414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa93df9d53f'
down_revision: Union[str, None] = '88a0f6bce924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('route', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'route')
    # ### end Alembic commands ###
